### ISSUE TITLE
Pagination not working with laravel 5.5 & october cms build 425

### ISSUE THREAD

**Issue by cygnetampatel** [OFFLINE-GmbH/oc-site-search-plugin#46] opened 2017-10-10 14:41 UTC
I have a facing issue in pagination.pagination is not working throw an error like this "**Method Illuminate\Pagination\LengthAwarePaginator::__toString() must not throw an exception, caught InvalidArgumentException: Please provide a valid cache path.**" 

issue in the view of pagination. if i set total no of result "0" or upto result per page. it's working fine.but no of result greater than per page. issue is arriving.

**Comment by tobias-kuendig** [comment] 2017-12-05 13:31
I am unable to reproduce this issue. The plugin is working on build 430 as expected.

The exception you posted is thrown by Laravel's view compiler. Maybe there is something wrong with your setup?

Maybe you can post some more details or code.

**Comment by host138** [comment] 2018-03-08 14:12
I get the same error when 1 character is in the search

**Comment by tobias-kuendig** [comment] 2018-03-08 15:36
Can you check if all these folders under `storage/framework` exist and are writeable by the webserver user?

* sessions
* views
* cache

**Comment by host138** [comment] 2018-03-09 11:34
Views folder doesn't exist

**Comment by tobias-kuendig** [comment] 2018-03-09 11:55
Thanks for your feedback. These folders have to exist for Laravel to work properly. I'm closing this issue since it's not a problem caused by the plugin.

**Closed by tobias-kuendig** 2018-03-09 11:55 UTC
Labels: bug
